# Generated by Django 3.2.7 on 2021-11-25 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalogo',
            fields=[
                ('idHotel', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=60, verbose_name='nombre')),
                ('Ubicacion', models.CharField(max_length=60, verbose_name='ubicacion')),
                ('Calificacion', models.IntegerField(default=0)),
                ('Direccion', models.CharField(max_length=60, verbose_name='direccion')),
                ('Descripcion', models.CharField(max_length=60, verbose_name='descripcion')),
                ('Correo', models.CharField(max_length=60, verbose_name='correo')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('idHabitacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipoHabitacion', models.CharField(max_length=30, verbose_name='tipoHabitacion')),
                ('capacidadHabitacion', models.IntegerField(default=0)),
                ('costoHabitacion', models.IntegerField(default=0)),
                ('descripcionHabitacion', models.CharField(max_length=300, verbose_name='descripcionHabitacion')),
                ('idHotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idCatalogo', to='cata1App.catalogo')),
            ],
        ),
    ]
